-- Run this in Supabase SQL Editor
create extension if not exists pgcrypto;

create table if not exists public.stock_items (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(14, 2) not null default 0,
  stock integer not null default 0,
  image_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  sold_at timestamptz not null default now(),
  stock_item_id bigint not null references public.stock_items(id) on update cascade on delete restrict,
  item_name text not null,
  unit_price numeric(14, 2) not null,
  qty integer not null check (qty > 0),
  total_price numeric(14, 2) not null,
  buyer_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  bought_at timestamptz not null default now(),
  description text,
  total_cost numeric(14, 2) not null default 0,
  created_at timestamptz not null default now()
);

create or replace function public.create_sale(
  p_stock_item_id bigint,
  p_qty integer,
  p_buyer_name text default null,
  p_sold_at timestamptz default now()
)
returns public.sales
language plpgsql
security definer
set search_path = public
as $$
declare
  item_row public.stock_items;
  inserted_sale public.sales;
  total numeric(14, 2);
begin
  if p_qty <= 0 then
    raise exception 'qty harus lebih dari 0';
  end if;

  select *
  into item_row
  from public.stock_items
  where id = p_stock_item_id
  for update;

  if not found then
    raise exception 'item tidak ditemukan';
  end if;

  if item_row.stock < p_qty then
    raise exception 'stok tidak cukup';
  end if;

  total := item_row.price * p_qty;

  update public.stock_items
  set stock = stock - p_qty
  where id = p_stock_item_id;

  insert into public.sales (
    sold_at,
    stock_item_id,
    item_name,
    unit_price,
    qty,
    total_price,
    buyer_name
  )
  values (
    p_sold_at,
    item_row.id,
    item_row.name,
    item_row.price,
    p_qty,
    total,
    nullif(trim(p_buyer_name), '')
  )
  returning * into inserted_sale;

  return inserted_sale;
end;
$$;

alter table public.stock_items enable row level security;
alter table public.sales enable row level security;
alter table public.expenses enable row level security;

-- Dev policy: open access. Tighten this in production.
drop policy if exists "dev_all_stock_items" on public.stock_items;
create policy "dev_all_stock_items"
on public.stock_items
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "dev_all_sales" on public.sales;
create policy "dev_all_sales"
on public.sales
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "dev_all_expenses" on public.expenses;
create policy "dev_all_expenses"
on public.expenses
for all
to anon, authenticated
using (true)
with check (true);

grant execute on function public.create_sale(bigint, integer, text, timestamptz) to anon, authenticated;

-- Optional sample data
insert into public.stock_items (name, price, stock, image_url)
select sample.name, sample.price, sample.stock, sample.image_url
from (
  values
    ('Kursi Minimalis', 350000::numeric, 12, null::text),
    ('Meja Samping', 275000::numeric, 8, null::text),
    ('Lampu Dekor', 180000::numeric, 4, null::text)
) as sample(name, price, stock, image_url)
where not exists (
  select 1 from public.stock_items existing where existing.name = sample.name
);
